import {test,expect} from '@playwright/test';
import {mkdir} from 'node:fs/promises';
test('homepage and mobile discovery render without overflow',async({page})=>{
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));await page.goto('/');await expect(page.getByRole('heading',{name:/Go somewhere/})).toBeVisible();await expect(page.locator('.tour-card')).toHaveCount(3);await page.waitForLoadState('networkidle');await mkdir('.local/screens',{recursive:true});await page.screenshot({path:'.local/screens/home-desktop.png',fullPage:true});expect(errors).toEqual([]);
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.local/screens/home-mobile.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.getByRole('button',{name:'Toggle menu'}).click();await page.getByRole('navigation',{name:'Main navigation'}).getByRole('link',{name:'Explore tours'}).click();await expect(page.getByRole('heading',{name:'Find your kind of elsewhere.'})).toBeVisible();await page.getByLabel('Search tours').fill('Goa');await expect(page.locator('.tour-card')).toHaveCount(2);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});
test('traveler can register, save a tour, book, pay, chat and cancel',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/register');await page.getByLabel('Your name').fill('Browser Traveler');await page.getByLabel('Email address',{exact:true}).fill(`browser-${Date.now()}@example.test`);await page.getByLabel('Password',{exact:true}).fill('Browser-test-password!');await page.getByRole('button',{name:'Start my next chapter'}).click();await expect(page).toHaveURL(/dashboard/);
 await page.goto('/tours?search=Goa');await expect(page.locator('.tour-card')).toHaveCount(2);await page.getByRole('button',{name:'Add to wishlist'}).first().click();await expect(page.getByRole('button',{name:'Remove from wishlist'})).toBeVisible();await page.goto('/wishlist');await expect(page.locator('.tour-card')).toHaveCount(1);await page.locator('.tour-card h3').click();await page.getByRole('link',{name:'Make this my next chapter'}).click();await page.getByRole('button',{name:/places left/}).first().click();await page.getByRole('button',{name:'Meet your travel party'}).click();await page.getByRole('button',{name:'Review my adventure'}).click();await page.getByRole('button',{name:'Continue to demo payment'}).click();await expect(page.getByText('Demo Payment — No real money will be charged.')).toBeVisible();await page.getByRole('button',{name:/Simulate .* payment/}).click();await expect(page.getByRole('heading',{name:'Your next chapter is confirmed.'})).toBeVisible();await page.getByRole('link',{name:'See my adventure'}).click();await expect(page.getByText('CONFIRMED',{exact:true})).toBeVisible();const bookingUrl=page.url();await page.screenshot({path:'.local/screens/booking.png',fullPage:true});
 await page.goto('/assistant');await page.getByRole('button',{name:'What hotel am I staying at?'}).click();await expect(page.locator('.chat-message.assistant')).toContainText('Goa Garden Retreat');await expect(page.locator('.chat-sources')).toContainText('TRV-');await page.screenshot({path:'.local/screens/chat.png',fullPage:true});
 await page.goto(bookingUrl);await page.getByRole('button',{name:'Cancel this booking'}).click();await page.getByRole('button',{name:'Confirm cancellation'}).click();await expect(page.getByText('CANCELLED',{exact:true})).toBeVisible();await expect(page.getByText('REFUNDED',{exact:true}).first()).toBeVisible();expect(errors).toEqual([]);
});
test('admin can manage knowledge and catalog with real saves',async({page})=>{
 await page.goto('/login');await page.getByLabel('Email address',{exact:true}).fill('aman@admin.com');await page.getByLabel('Password',{exact:true}).fill(process.env.SEED_ADMIN_PASSWORD!);await page.getByRole('button',{name:'Let’s go',exact:true}).click();await expect(page).toHaveURL(/admin/);await expect(page.getByRole('heading',{name:'Good journeys start here.'})).toBeVisible();await page.screenshot({path:'.local/screens/admin.png',fullPage:true});
 await page.goto('/admin/categories');await page.getByRole('button',{name:'Add category'}).click();const name=`Browser category ${Date.now()}`;await page.getByRole('dialog').getByLabel('Name',{exact:true}).fill(name);await page.getByRole('dialog').getByLabel('Description').fill('A category created during browser verification.');await page.getByRole('button',{name:'Save changes'}).click();await expect(page.getByRole('cell',{name,exact:true})).toBeVisible();await page.getByRole('row').filter({hasText:name}).getByRole('button',{name:'Delete',exact:true}).click();await page.getByRole('button',{name:'Confirm deletion'}).click();await expect(page.getByRole('cell',{name,exact:true})).toHaveCount(0);
 await page.goto('/admin/rag');await page.getByRole('button',{name:'Add knowledge'}).click();await page.getByLabel('Source title').fill(name);await page.getByLabel('Source content').fill('Browser verification knowledge: pack a reusable water bottle and comfortable walking shoes.');await page.getByRole('button',{name:'Save changes'}).click();await expect(page.getByRole('cell',{name,exact:true})).toBeVisible();await page.getByRole('row').filter({hasText:name}).getByRole('button',{name:'Delete',exact:true}).click();await page.getByRole('button',{name:'Confirm deletion'}).click();await expect(page.getByRole('cell',{name,exact:true})).toHaveCount(0);
});
